#!/bin/bash
# save as time-signal.sh

min=$(date +%M)


if [[ $min -gt 14 && $min -le 31 ]]; then
     echo -ne "\a"

elif [[ $min -gt 30 && $min -le 46 ]]; then
        echo -ne "\a"
        echo -ne "\a"

elif [[ $min -gt 45 && $min -lt 60 ]]; then
        echo -ne "\a"
        echo -ne "\a"
        echo -ne "\a"
else
        echo "No Chime"
fi
