#!/bin/bash
#save as newer.sh
# Its a scrip for displaying recently created files based on time
echo "let us search for the new file"
echo " Your present directory is:" 
pwd;
echo "your new file is ..............."
echo "got it!"
ls -t1 |
head -n1; 
