#!/bin/bash
#save as newer.sh
# Its a scrip for displaying recently created files based on time
echo "let us search for the newest file"
echo " Your present directory is:" 
pwd;
echo "your newest file is ..............."
ls -t1|
head -n1; 
