#!/bin/bash

if [ $# -ge 1 ] then             # checking whether the attributes given is greater than or equal to 1 in if condition

        echo "this is a test"     
else
        echo "this is NOT a test"
fi
